work_dir: ./output/ctrgcn_V1_J

# feeder
feeder: GCN.dataset.feeder.Feeder
train_feeder_args: 
  data_path: GCN/data/V1.npz
  data_split: train
  p_interval: [0.5, 1]
  window_size: 5
  bone: False
  vel: True

test_feeder_args:
  data_path: GCN/data/V1.npz
  data_split: test
  p_interval: [0.95]
  window_size: 5
  bone: False
  vel: True

# model
model: GCN.model.ctrgcn_xy.Model
model_args:
  num_class: 2
  num_point: 17
  num_person: 1
  graph: GCN.graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.05
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
