# command line: /home/fds/anaconda3/envs/tennisone/lib/python3.9/site-packages/uvicorn/__main__.py backend.main:app --host 0.0.0.0 --port 8000

base_lr: 0.05
batch_size: 64
config: /data-home/liujinfu/UAV/config/V1_j_3D.yaml
device:
- 0
eval_interval: 5
feeder: GCN.dataset.feeder.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: GCN.model.ctrgcn_xy.Model
model_args:
  graph: GCN.graph.Simcc.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 2
  num_person: 1
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 65
num_worker: 8
optimizer: SGD
phase: test
print_log: true
save_epoch: 10
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 55
test_batch_size: 64
test_feeder_args:
  bone: true
  data_path: GCN/data/V1.npz
  data_split: test
  p_interval:
  - 0.95
  vel: false
  window_size: 5
train_feeder_args:
  bone: true
  data_path: GCN/data/V1.npz
  data_split: train
  p_interval:
  - 0.5
  - 1
  vel: false
  window_size: 5
video_file: null
warm_up_epoch: 5
weight_decay: 0.0004
weights: ./GCN/work_dir/b/runs-65-715.pt
work_dir: ./GCN/work_dir/b
